"""adiciona campo email a restaurantes

Revision ID: 50da5c2d9a1f
Revises: 774c449649a7
Create Date: 2024-06-09 21:13:16.461836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50da5c2d9a1f'
down_revision = '774c449649a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
