"""Adicionar campos segmento e cnpj ao modelo Restaurante

Revision ID: 774c449649a7
Revises: 6302b270345a
Create Date: 2024-06-09 20:45:38.014467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '774c449649a7'
down_revision = '6302b270345a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=False)

    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.alter_column('telefone',
               existing_type=mysql.VARCHAR(length=11),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=11),
               existing_nullable=False)

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
